from pydantic import BaseModel, ConfigDict
from typing import List, Optional, Dict, Any
from .tax import TaxResponse, TaxLabResponse
from .investment import InvestmentResponse, InvestmentLabResponse
from .insurance import InsuranceLabResponse
from .retirement import RetirementLabResponse, RetirementProjectionResponse, OptimizationResponse


class AdvisoryPlanAction(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    phase: str
    order: int
    title: str
    description: str
    rationale: str
    reference: str


class AdvisoryPlan(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    liquidity_reserve: Optional[Dict[str, Any]] = None
    debt_repayment: Optional[Dict[str, Any]] = None
    insurance_gaps: List[AdvisoryPlanAction]
    tax_optimizations: List[AdvisoryPlanAction]
    investment_plan: List[AdvisoryPlanAction]
    retirement_plan: List[AdvisoryPlanAction]


class IntegratedAdvisoryPlan(BaseModel):
    """Cross-domain action plan generated by the deterministic advisory engine."""

    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    as_of: str
    scope: str
    household_kpis: Dict[str, Any]
    protection_needs: Dict[str, Any]
    portfolio_suitability: Dict[str, Any]
    stress_tests: List[Dict[str, Any]]
    action_plan: List[Dict[str, Any]]
    plan_feasible: bool
    financial_resilience_score: int
    score_components: Dict[str, float]
    assumptions: List[str]


class FullAnalysisResponse(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    tax: TaxResponse
    tax_lab: TaxLabResponse
    investment: InvestmentResponse
    investment_lab: InvestmentLabResponse
    insurance: List[Dict[str, Any]]
    insurance_lab: InsuranceLabResponse
    retirement: RetirementProjectionResponse
    retirement_lab: RetirementLabResponse
    optimization: OptimizationResponse
    advisory_plan: IntegratedAdvisoryPlan
    risk_suitability: Optional[Dict[str, Any]] = None
    model_metadata: Dict[str, Any]


class ConsultantInsightResponse(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    insight: str
    analysis: FullAnalysisResponse


class ChatResponse(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    reply: str


class HealthResponse(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False, extra="allow")
    status: str
    service: str
    version: str
    model_year: int
